name: hello-world-workflow
on:
  push: 
    branches: main
      --main
  pull_request:
    branches:
      --main
  workflow-dispatch:    
jobs:
  hello:
    steps:
      -name: hello-world
      run: echo "Hello world"
  goodbye:
    steps:
      -name: goodbye-world
      run: echo "Goodbye world"